Print[$InstallationDirectory ]
Print[$BaseDirectory ]
Print[$UserBaseDirectory]
Print[$RootDirectory ]
Print[$HomeDirectory]
Print[$UserDocumentsDirectory ]
Print[$TemporaryDirectory ]
Print[$InitialDirectory ]
Print[$Path ]
Print[$LibraryPath ]
Print[$DefaultPath ]
